#!/bin/bash
## Extract and format Pikachu's data using jq, awk, and sed
jq -r '"\(.name) \(.types[0].type.name) \(.weight) \(.height)"' data.json | \
sed 's/^/Name Type Weight Height: /' | \
awk '{name=toupper(substr($2,1,1)) substr($2,2);
 type=toupper(substr($3,1,1)) substr($3,2);
 printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n", name, type, $4/10, $5/10}'

